/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oz_code_opencv_imgproc_ImgProc */

#ifndef _Included_oz_code_opencv_imgproc_ImgProc
#define _Included_oz_code_opencv_imgproc_ImgProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oz_code_opencv_imgproc_ImgProc
 * Method:    imgGray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_oz_code_opencv_imgproc_ImgProc_imgGray
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
